// <auto-generated />
using System;
using MVC_DOAN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_DOAN.Migrations
{
    [DbContext(typeof(DoanContext))]
    [Migration("20231130111543_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_DOAN.Models.Chitietdon", b =>
                {
                    b.Property<int>("Madon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madon"));

                    b.Property<int?>("Dongia")
                        .HasColumnType("int");

                    b.Property<int?>("SanphamId")
                        .HasColumnType("int");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("TaikhoanId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Madon");

                    b.HasIndex("TaikhoanId");

                    b.ToTable("Chitietdons");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Ctgh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SanphamId")
                        .HasColumnType("int");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("TaikhoanId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TaikhoanId");

                    b.ToTable("Ctghs");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Danhgia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Danhgiaa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<int?>("SanphamId")
                        .HasColumnType("int");

                    b.Property<string>("TaikhoanId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SanphamId");

                    b.HasIndex("TaikhoanId");

                    b.ToTable("Danhgias");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Diachi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diachichitiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotennguoinhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaikhoanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaikhoanId");

                    b.ToTable("Diachis");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Donhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiachiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaygiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phuongthucthanhtoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaikhoanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Tongtien")
                        .HasColumnType("int");

                    b.Property<string>("Trangthaidonhang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthaithanhtoan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiachiId");

                    b.HasIndex("TaikhoanId");

                    b.ToTable("Donhangs");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Loaisanpham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TaikhoanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tenlsp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tinhtrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaikhoanId");

                    b.ToTable("Loaisanphams");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Phiship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Phi")
                        .HasColumnType("int");

                    b.Property<string>("Quan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaikhoanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Thoigian")
                        .HasColumnType("int");

                    b.Property<string>("Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaikhoanId");

                    b.ToTable("Phiships");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Sanpham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Dongia")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaisanphamId")
                        .HasColumnType("int");

                    b.Property<int?>("Soluongdaban")
                        .HasColumnType("int");

                    b.Property<int?>("Soluongtonkho")
                        .HasColumnType("int");

                    b.Property<string>("TaikhoanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tensp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tinhtrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaisanphamId");

                    b.HasIndex("TaikhoanId");

                    b.ToTable("Sanphams");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Taikhoan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matkhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phanloai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Chitietdon", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Taikhoan", "Taikhoan")
                        .WithMany("Chitietdons")
                        .HasForeignKey("TaikhoanId");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Ctgh", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Taikhoan", "Taikhoan")
                        .WithMany("Ctghs")
                        .HasForeignKey("TaikhoanId");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Danhgia", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Sanpham", "Sanpham")
                        .WithMany()
                        .HasForeignKey("SanphamId");

                    b.HasOne("MVC_DOAN.Models.Taikhoan", "Taikhoan")
                        .WithMany("Danhgias")
                        .HasForeignKey("TaikhoanId");

                    b.Navigation("Sanpham");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Diachi", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Taikhoan", "Taikhoan")
                        .WithMany("Diachi")
                        .HasForeignKey("TaikhoanId");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Donhang", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Diachi", "Diachi")
                        .WithMany()
                        .HasForeignKey("DiachiId");

                    b.HasOne("MVC_DOAN.Models.Taikhoan", "Taikhoan")
                        .WithMany("Donhangs")
                        .HasForeignKey("TaikhoanId");

                    b.Navigation("Diachi");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Loaisanpham", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Taikhoan", "Taikhoan")
                        .WithMany("Loaisanphams")
                        .HasForeignKey("TaikhoanId");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Phiship", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Taikhoan", "Taikhoan")
                        .WithMany("Phiships")
                        .HasForeignKey("TaikhoanId");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Sanpham", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Loaisanpham", "Loaisanpham")
                        .WithMany()
                        .HasForeignKey("LoaisanphamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_DOAN.Models.Taikhoan", "Taikhoan")
                        .WithMany("Sanphams")
                        .HasForeignKey("TaikhoanId");

                    b.Navigation("Loaisanpham");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Taikhoan", b =>
                {
                    b.Navigation("Chitietdons");

                    b.Navigation("Ctghs");

                    b.Navigation("Danhgias");

                    b.Navigation("Diachi");

                    b.Navigation("Donhangs");

                    b.Navigation("Loaisanphams");

                    b.Navigation("Phiships");

                    b.Navigation("Sanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
