// <auto-generated />
using System;
using MVC_DOAN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_DOAN.Migrations
{
    [DbContext(typeof(DoanContext))]
    partial class DoanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_DOAN.Models.Chitietdon", b =>
                {
                    b.Property<string>("Madon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("madon");

                    b.Property<string>("Masp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("masp");

                    b.Property<int?>("Dongia")
                        .HasColumnType("int")
                        .HasColumnName("dongia");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("soluong");

                    b.HasKey("Madon", "Masp")
                        .HasName("PK__CHITIETD__3C460110B16E51DC");

                    b.HasIndex("Masp");

                    b.ToTable("CHITIETDON", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Ctgh", b =>
                {
                    b.Property<string>("Matk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("matk");

                    b.Property<string>("Masp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("masp");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("soluong");

                    b.HasKey("Matk", "Masp")
                        .HasName("PK__CTGH__4D83697130C5FD7B");

                    b.HasIndex("Masp");

                    b.ToTable("CTGH", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Danhgium", b =>
                {
                    b.Property<string>("Madg")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("madg");

                    b.Property<string>("Danhgiaa")
                        .HasColumnType("text")
                        .HasColumnName("danhgiaa");

                    b.Property<string>("Masp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("masp");

                    b.Property<string>("Matk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("matk");

                    b.Property<int?>("Rate")
                        .HasColumnType("int")
                        .HasColumnName("rate");

                    b.HasKey("Madg")
                        .HasName("PK__DANHGIA__7A21E026E8F4641C");

                    b.HasIndex("Masp");

                    b.HasIndex("Matk");

                    b.ToTable("DANHGIA", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Diachi", b =>
                {
                    b.Property<string>("Madc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("madc");

                    b.Property<string>("Diachichitiet")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("diachichitiet");

                    b.Property<string>("Hotennguoinhan")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hotennguoinhan");

                    b.Property<string>("Huyen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("huyen");

                    b.Property<string>("Matk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("matk");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("Tinh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tinh");

                    b.HasKey("Madc")
                        .HasName("PK__DIACHI__7A21E05ACDDAFB12");

                    b.ToTable("DIACHI", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Donhang", b =>
                {
                    b.Property<string>("Madon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("madon");

                    b.Property<string>("Madc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("madc");

                    b.Property<DateTime?>("Ngaygiao")
                        .HasColumnType("date")
                        .HasColumnName("ngaygiao");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("ngaytao");

                    b.Property<string>("Phuongthucthanhtoan")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("phuongthucthanhtoan")
                        .IsFixedLength();

                    b.Property<int?>("Tongtien")
                        .HasColumnType("int")
                        .HasColumnName("tongtien");

                    b.Property<string>("Trangthaidonhang")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("trangthaidonhang")
                        .IsFixedLength();

                    b.Property<string>("Trangthaithanhtoan")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("trangthaithanhtoan")
                        .IsFixedLength();

                    b.HasKey("Madon")
                        .HasName("PK__DONHANG__0BE41677DB87ED07");

                    b.HasIndex("Madc");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Loaisanpham", b =>
                {
                    b.Property<string>("Malsp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("malsp");

                    b.Property<string>("Tenlsp")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tenlsp");

                    b.Property<string>("Tinhtrang")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("tinhtrang")
                        .IsFixedLength();

                    b.HasKey("Malsp")
                        .HasName("PK__LOAISANP__15F47678578B3695");

                    b.ToTable("LOAISANPHAM", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Phiship", b =>
                {
                    b.Property<string>("Maphi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("maphi");

                    b.Property<int?>("Phi")
                        .HasColumnType("int")
                        .HasColumnName("phi");

                    b.Property<string>("Quan")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("quan");

                    b.Property<int?>("Thoigian")
                        .HasColumnType("int")
                        .HasColumnName("thoigian");

                    b.Property<string>("Tinh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tinh");

                    b.HasKey("Maphi")
                        .HasName("PK__PHISHIP__0AFFEDDB0F87A23F");

                    b.ToTable("PHISHIP", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Sanpham", b =>
                {
                    b.Property<string>("Masp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("masp");

                    b.Property<int?>("Dongia")
                        .HasColumnType("int")
                        .HasColumnName("dongia");

                    b.Property<string>("Img")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("img");

                    b.Property<string>("Malsp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("malsp");

                    b.Property<int?>("Soluongdaban")
                        .HasColumnType("int")
                        .HasColumnName("soluongdaban");

                    b.Property<int?>("Soluongtonkho")
                        .HasColumnType("int")
                        .HasColumnName("soluongtonkho");

                    b.Property<string>("Tensp")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tensp");

                    b.Property<string>("Tinhtrang")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("tinhtrang")
                        .IsFixedLength();

                    b.HasKey("Masp")
                        .HasName("PK__SANPHAM__7A217672565A9A74");

                    b.HasIndex("Malsp");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Taikhoan", b =>
                {
                    b.Property<string>("Matk")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("matk");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("matkhau");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("Phanloai")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("phanloai")
                        .IsFixedLength();

                    b.HasKey("Matk")
                        .HasName("PK__TAIKHOAN__7A217E16F62E120F");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("MVC_DOAN.Models.Chitietdon", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Donhang", "MadonNavigation")
                        .WithMany("Chitietdons")
                        .HasForeignKey("Madon")
                        .IsRequired()
                        .HasConstraintName("FK_DH_CTD");

                    b.HasOne("MVC_DOAN.Models.Sanpham", "MaspNavigation")
                        .WithMany("Chitietdons")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK_SP_CTD");

                    b.Navigation("MadonNavigation");

                    b.Navigation("MaspNavigation");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Ctgh", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Sanpham", "MaspNavigation")
                        .WithMany("Ctghs")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK_SP_GH");

                    b.HasOne("MVC_DOAN.Models.Taikhoan", "MatkNavigation")
                        .WithMany("Ctghs")
                        .HasForeignKey("Matk")
                        .IsRequired()
                        .HasConstraintName("FK_TK_GH");

                    b.Navigation("MaspNavigation");

                    b.Navigation("MatkNavigation");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Danhgium", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Sanpham", "MaspNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("Masp")
                        .HasConstraintName("FK_SP_DG");

                    b.HasOne("MVC_DOAN.Models.Taikhoan", "MatkNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("Matk")
                        .HasConstraintName("FK_TK_DG");

                    b.Navigation("MaspNavigation");

                    b.Navigation("MatkNavigation");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Donhang", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Diachi", "MadcNavigation")
                        .WithMany("Donhangs")
                        .HasForeignKey("Madc")
                        .HasConstraintName("FK_DH_DC");

                    b.Navigation("MadcNavigation");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Sanpham", b =>
                {
                    b.HasOne("MVC_DOAN.Models.Loaisanpham", "MalspNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Malsp")
                        .HasConstraintName("FK_SP_LSP");

                    b.Navigation("MalspNavigation");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Diachi", b =>
                {
                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Donhang", b =>
                {
                    b.Navigation("Chitietdons");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Loaisanpham", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Sanpham", b =>
                {
                    b.Navigation("Chitietdons");

                    b.Navigation("Ctghs");

                    b.Navigation("Danhgia");
                });

            modelBuilder.Entity("MVC_DOAN.Models.Taikhoan", b =>
                {
                    b.Navigation("Ctghs");

                    b.Navigation("Danhgia");
                });
#pragma warning restore 612, 618
        }
    }
}
